name: Deploy

on: [push]
#on:
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: test
          location: europe-west1-b
          credentials: ${{ secrets.gcp_credentials }}

      - run: kubectl cluster-info
